import * as THREE from "three";
'use strict';
const $=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x)),key=c=>c.join(','),eq=(a,b)=>a&&b&&key(a)===key(b),dist=(a,b)=>Math.abs(a[0]-b[0])+Math.abs(a[1]-b[1]);
const statuses=['idle','to_pickup','pickup','to_dropoff','dropoff','to_charge_queue','waiting_charge','to_charge_port','docking','charging','charge_egress','reposition','recovering','hold'];
const group=s=>s==='idle'?'IDLE':s==='hold'||s==='recovering'?'HOLD':statuses.indexOf(s)>=5&&statuses.indexOf(s)<=10?'CHARGE':'WORK';
const specs={L:{capacity_wh:180,speed_mps:2,payload_capacity_kg:20,movement_wh_m:.035},M:{capacity_wh:300,speed_mps:1,payload_capacity_kg:50,movement_wh_m:.055},H:{capacity_wh:450,speed_mps:.75,payload_capacity_kg:100,movement_wh_m:.085}};
let map,frames=[],frame,idx=-1,time=0,playing=false,selected=0,isMock=true,live=false,scene,camera,renderer,world,dynamic,robots=new Map(),grid,routeLayer,resLayer,heatLayer,taskLayer,portMeshes=new Map();
let liveSpeed=1,livePaused=false,liveFinished=false,liveBuffered=false;
const flags={grid:false,labels:true,routes:false,reservations:false,heatmap:false,fullLabels:false,xray:false};
function error(e){$('error').textContent='Lỗi dữ liệu / hiển thị: '+e.message;$('error').style.display='block';playing=false;$('play').textContent='▶ Phát';setTimeout(()=>$('error').style.display='none',12000)}
function assert(v,m){if(!v)throw Error(m)}
function presetMap(name='A'){
 // Chép đúng make_map trong maps.py được cung cấp, không sinh layout giả định.
 const walls=[];for(const x of [8,16,24,32])for(const [a,b] of name==='A'?[[5,10],[16,23]]:[[5,12],[18,24]])for(let u=x;u<x+3;u++)for(let y=a;y<b;y++)walls.push([u,y]);
 let pickups=[[7,6],[15,8],[11,18],[19,20],[23,6],[31,8],[27,18],[35,20],[7,22],[15,22],[23,22],[31,22]];
 if(name==='B')pickups=pickups.map(([x,y])=>[x,y===18?15:y]);
 const q0=[1,2,3,4].map(x=>[x,name==='A'?3:13]),q1=[35,36,37,38].map(x=>[x,name==='A'?26:15]);
 return {name,width:40,height:30,walls,pickups,dropoffs:[[3,6],[36,6],[3,24],[36,24]],parking:[1,28].flatMap(y=>[5,6,7,11,12,13,19,20,21,28,29,30].map(x=>[x,y])),ports:[[2,2],[3,2],[36,27],[37,27]].map((c,id)=>({id,cell:[c[0],name==='A'?c[1]:14],station:id<2?0:1,power_w:600,compatible:id<2?['L','M']:['L','M','H']})),queue_cells:{0:q0,1:q1},blocked_edges:[],source:'maps.py / make_map; power=600 W demo config'};
}
function normalizeMap(m){assert(m&&typeof m==='object'&&Array.isArray(m.ports),'Map JSON thiếu danh sách ports');m=clone(m);m.queue_cells??={};m.ports=m.ports.map(p=>{let s=p.station??p.station_id;if(p.queue_cells)m.queue_cells[s]=p.queue_cells;return {...p,cell:p.cell??p.position,station:s,compatible:p.compatible??p.compatible_kinds}});m.blocked_edges??=[];return m}
function validMap(m){assert(m.width===40&&m.height===30,'Map cần width=40, height=30');assert(Array.isArray(m.walls)&&Array.isArray(m.pickups)&&Array.isArray(m.dropoffs)&&Array.isArray(m.parking)&&Array.isArray(m.ports),'Map thiếu các danh sách bắt buộc');const wall=new Set(m.walls.map(key));const cell=c=>assert(Array.isArray(c)&&c.length===2&&c.every(Number.isInteger)&&c[0]>=0&&c[0]<40&&c[1]>=0&&c[1]<30,'Ô ngoài map / sai tọa độ: '+JSON.stringify(c));m.walls.forEach(cell);for(const c of [...m.pickups,...m.dropoffs,...m.parking,...m.ports.map(p=>p.cell),...Object.values(m.queue_cells).flat()]){cell(c);assert(!wall.has(key(c)),'Endpoint nằm trong kệ '+c)}assert(new Set(m.ports.map(p=>p.id)).size===m.ports.length,'Trùng ID cổng');for(const p of m.ports)assert(Number.isFinite(p.power_w)&&p.power_w>0&&Array.isArray(p.compatible),'Cổng thiếu power_w/compatible');return m}
function loadMap(raw){const m=validMap(normalizeMap(raw));map=m;buildWorld();return m}
function validateFrame(f,m,prev){assert(Number.isFinite(f.t)&&Number.isFinite(f.observed_at)&&f.observed_at<=f.t,'t/observed_at không hợp lệ');assert(!prev||f.t>prev.t,'Timestamp phải tăng nghiêm ngặt');assert(Array.isArray(f.robots)&&Array.isArray(f.tasks)&&Array.isArray(f.ports),'Thiếu robots/tasks/ports');const wall=new Set(m.walls.map(key)),occupied=new Map(),ids=new Set();const checkCell=c=>assert(Array.isArray(c)&&c.length===2&&c.every(Number.isInteger)&&c[0]>=0&&c[0]<m.width&&c[1]>=0&&c[1]<m.height&&!wall.has(key(c)),'Ô robot/endpoint ngoài map hoặc trong kệ: '+c);
 for(const r of f.robots){assert(Number.isInteger(r.id)&&!ids.has(r.id),'Robot ID phải nguyên và không trùng');ids.add(r.id);checkCell(r.cell);assert(specs[r.type]&&statuses.includes(r.status),'Loại/trạng thái robot sai');assert(Number.isFinite(r.soc)&&r.soc>=0&&r.soc<=1,'SoC ngoài [0,1]');assert(Number.isFinite(r.load_kg)&&r.load_kg>=0,'load_kg sai');let cells=[r.cell];if(r.move_to){checkCell(r.move_to);assert(dist(r.cell,r.move_to)===1,'move_to phải đúng một cạnh');assert(r.edge_duration_s>0&&r.move_remaining_s>=0&&r.move_remaining_s<=r.edge_duration_s,'Thiếu/sai thời gian cạnh');cells.push(r.move_to)}for(const c of cells){assert(!occupied.has(key(c))||occupied.get(key(c))===r.id,'Hai robot chiếm/đặt chỗ endpoint '+c);occupied.set(key(c),r.id)}if(prev){const p=prev.robots.find(p=>p.id===r.id);if(p)assert(dist(p.cell,r.cell)<=1,'Robot nhảy quá một cạnh: hãy xuất replay mỗi tick 0.5 s')}}
 for(const r of f.robots){for(const c of r.route??[])checkCell(c);for(const k of ['reservations','heatmap'])assert(f[k]===undefined||Array.isArray(f[k]),k+' phải là array')}for(const v of f.reservations??[])checkCell(v.cell);for(const h of f.heatmap??[]){checkCell(h.cell);assert(Number.isFinite(h.value)&&h.value>=0&&h.value<=1,'Heatmap value phải ở [0,1]')}for(const c of f.corridors??[]){assert(Array.isArray(c.cells),'Corridor thiếu cells');c.cells.forEach(checkCell);(c.passing_cells??[]).forEach(checkCell);if(c.direction)c.direction.forEach(checkCell)}for(const t of f.tasks){checkCell(t.pickup);checkCell(t.dropoff);assert(Number.isFinite(t.created)&&t.created<=f.t,'Task chưa tới thời điểm quan sát');assert(Number.isFinite(t.kg)&&Number.isFinite(t.deadline)&&[1,2,3].includes(t.priority),'Task sai kg/deadline/priority')}
 for(const p of f.ports){assert(m.ports.some(x=>x.id===p.id),'ID cổng không thuộc map');for(const b of p.bookings??[])assert(Number.isFinite(b.start)&&Number.isFinite(b.end)&&b.end>=b.start&&(b.known_at??f.t)<=f.t,'Booking sai thời gian / lộ tương lai');assert(p.charging_robot==null||p.charging_robot===p.occupied_by,'Cổng nạp phải bị chiếm bởi cùng robot')}
 for(const c of f.blocked_cells??[])checkCell(c);for(const r of f.robots)if(r.move_to){assert(!(f.blocked_cells??[]).some(c=>eq(c,r.move_to)),'Robot đang đi vào ô block');assert(![...m.blocked_edges,...f.blocked_edges??[]].some(e=>eq(e[0],r.cell)&&eq(e[1],r.move_to)||eq(e[1],r.cell)&&eq(e[0],r.move_to)),'Robot đang đi qua cạnh block')}for(const e of f.blocked_edges??[]){checkCell(e[0]);checkCell(e[1]);assert(dist(...e)===1,'blocked edge không kề nhau')}
 assert(!f.decision||f.decision.profile==null||[0,1,2,3,4,5].includes(f.decision.profile),'Profile ngoài 0–5');return f;
}
function parseReplay(s){try{return JSON.parse(s)}catch{try{return s.split(/\r?\n/).filter(x=>x.trim()).map((x,i)=>{try{return JSON.parse(x)}catch{throw Error('JSONL lỗi dòng '+(i+1))}})}catch(e){throw e}}}
function install(data,overrideMap){let fs=Array.isArray(data)?data:data.frames;assert(Array.isArray(fs)&&fs.length,'Replay không có frames');const m=validMap(normalizeMap(overrideMap??(Array.isArray(data)?undefined:data.map)??map));let prev;fs.forEach(f=>{validateFrame(f,m,prev);prev=f});loadMap(m);frames=fs;isMock=data.mock===true;live=false;$('seek').disabled=false;$('play').disabled=false;time=fs[0].t;idx=-1;playing=false;$('play').textContent='▶ Phát';$('seek').min=time;$('seek').max=fs.at(-1).t;update();}
const materials=new Map();let boxGeo;
function mat(color){if(!materials.has(color))materials.set(color,new THREE.MeshStandardMaterial({color,roughness:.7,metalness:.15}));return materials.get(color)}
function box(parent,c,w,h,d,color,y=0){const o=new THREE.Mesh(boxGeo,mat(color));o.scale.set(w,h,d);o.position.set(c[0]+.5,y+h/2,c[1]+.5);parent.add(o);return o}
function disposeGroup(g){if(!g)return;g.traverse(o=>{if(o.userData.ownTexture){o.material.map.dispose();o.material.dispose()}if(o.userData.ownGeo)o.geometry.dispose()});g.removeFromParent()}
function textSprite(text,c,color='#cae1ed',size=1){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=96;const ctx=canvas.getContext('2d');ctx.font='bold 44px sans-serif';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(text,256,62);const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,depthTest:true,transparent:true}));s.scale.set(size*5.33,size,1);s.position.set(c[0]+.5,.12,c[1]+.5);s.userData.ownTexture=true;return s}
function line(parent,cells,color=0x58ddc1,y=.12){if(cells.length<2)return;const g=new THREE.BufferGeometry().setFromPoints(cells.map(c=>new THREE.Vector3(c[0]+.5,y,c[1]+.5)));const o=new THREE.Line(g,new THREE.LineBasicMaterial({color}));o.userData.ownGeo=true;const old=o.material;o.userData.lineMat=true;parent.add(o);return o}
function clean(g){if(!g)return;g.traverse(o=>{if(o.userData.lineMat)o.material.dispose();for(const m of o.userData.materials??[])m.dispose();for(const t of o.userData.textures??[])t.dispose();if(o.isInstancedMesh)o.dispose()});disposeGroup(g)}
// Lớp hình ảnh thuần túy: không tính planner, KPI hay năng lượng.
let sun,visualReady=false,hovered=null,lastVisualT=null,visualDt=0;
let rackGroups=[],visualPort=new Map(),sharedGeo={},sharedTex={},floorMaterial;
const QUALITY={low:{dpr:1,shadow:0},medium:{dpr:1.5,shadow:1024},high:{dpr:2,shadow:2048}};
const palette={navy:0x101c28,steel:0x667984,blue:0x2c638a,orange:0xc58142,yellow:0xcbb465};
function seeded(seed){return()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296}}
function canvasTexture(w,h,paint){const c=document.createElement('canvas');c.width=w;c.height=h;paint(c.getContext('2d'),w,h);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function visualAssets(){if(visualReady)return;visualReady=true;
 sharedTex.contact=canvasTexture(128,128,(c,w,h)=>{const g=c.createRadialGradient(w/2,h/2,12,w/2,h/2,64);g.addColorStop(0,'rgba(0,0,0,0.40)');g.addColorStop(.65,'rgba(0,0,0,0.19)');g.addColorStop(1,'rgba(0,0,0,0)');c.fillStyle=g;c.fillRect(0,0,w,h)});
 sharedTex.carton=canvasTexture(128,128,(c,w,h)=>{c.fillStyle='#c4a278';c.fillRect(0,0,w,h);const rnd=seeded(99);for(let i=0;i<1600;i++){c.fillStyle=rnd()>.5?'#c0a078':'#c8a77e';c.fillRect(rnd()*w,rnd()*h,2,1)}c.fillStyle='#a78b62';c.fillRect(58,0,12,h);c.fillStyle='#dfd6be';c.fillRect(14,50,31,24);c.fillStyle='#45545b';for(let i=0;i<12;i++)c.fillRect(18+i*2,55,1,12)});
 sharedTex.hazard=canvasTexture(128,128,(c,w,h)=>{c.fillStyle='#d0b363';c.fillRect(0,0,w,h);c.fillStyle='#22303a';for(let i=-128;i<256;i+=32){c.beginPath();c.moveTo(i,0);c.lineTo(i+16,0);c.lineTo(i+144,128);c.lineTo(i+128,128);c.fill()}});
 sharedGeo.plane=new THREE.PlaneGeometry(1,1);sharedGeo.ring=new THREE.RingGeometry(.37,.415,40);sharedGeo.energyRing=new THREE.RingGeometry(.31,.35,40);
 sharedGeo.round=roundedShape(.5,.5,.18,.07);sharedGeo.cylinder=new THREE.CylinderGeometry(1,1,1,12);
}
function roundedShape(w,d,h,r){const sh=new THREE.Shape();sh.moveTo(-w/2+r,-d/2);sh.lineTo(w/2-r,-d/2);sh.quadraticCurveTo(w/2,-d/2,w/2,-d/2+r);sh.lineTo(w/2,d/2-r);sh.quadraticCurveTo(w/2,d/2,w/2-r,d/2);sh.lineTo(-w/2+r,d/2);sh.quadraticCurveTo(-w/2,d/2,-w/2,d/2-r);sh.lineTo(-w/2,-d/2+r);sh.quadraticCurveTo(-w/2,-d/2,-w/2+r,-d/2);const g=new THREE.ExtrudeGeometry(sh,{depth:h,bevelEnabled:true,bevelSegments:1,steps:1,bevelSize:.018,bevelThickness:.012,curveSegments:3});g.rotateX(-Math.PI/2);return g}
// Gộp các bộ phận có màu vertex vào một draw call, geometry dùng chung giữa robot cùng loại.
function mergeParts(parts){const pos=[],normal=[],colors=[],uvs=[];for(const p of parts){let g=p.geo.clone();if(g.index){const old=g;g=g.toNonIndexed();old.dispose()}const m=new THREE.Matrix4().compose(new THREE.Vector3(...(p.at??[0,0,0])),new THREE.Quaternion().setFromEuler(new THREE.Euler(...(p.rot??[0,0,0]))),new THREE.Vector3(...(p.scale??[1,1,1])));g.applyMatrix4(m);let c=new THREE.Color(p.color??0xffffff);for(let i=0;i<g.attributes.position.count;i++){pos.push(g.attributes.position.getX(i),g.attributes.position.getY(i),g.attributes.position.getZ(i));normal.push(g.attributes.normal.getX(i),g.attributes.normal.getY(i),g.attributes.normal.getZ(i));colors.push(c.r,c.g,c.b);uvs.push(g.attributes.uv?.getX(i)??0,g.attributes.uv?.getY(i)??0)}g.dispose()}let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(normal,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));return g}
function instanced(parent,entries,material,geometry=boxGeo,cast=false){if(!entries.length)return null;const mesh=new THREE.InstancedMesh(geometry,material,entries.length),o=new THREE.Object3D();for(let i=0;i<entries.length;i++){const p=entries[i];o.position.set(...p.at);o.rotation.set(...(p.rot??[0,0,0]));o.scale.set(...(p.scale??[1,1,1]));o.updateMatrix();mesh.setMatrixAt(i,o.matrix);if(p.color!==undefined)mesh.setColorAt(i,new THREE.Color(p.color))}mesh.castShadow=cast;mesh.receiveShadow=true;parent.add(mesh);return mesh}
function ownedMaterial(parent,material){(parent.userData.materials??=[]).push(material);return material}
function stampFloor(){return canvasTexture(2048,1536,(c,w,h)=>{const S=w/40,rnd=seeded(604);c.fillStyle='#465661';c.fillRect(0,0,w,h);for(let i=0;i<70000;i++){let v=rnd()>.5?255:0;c.fillStyle=`rgba(${v},${v},${v},.024)`;c.fillRect(rnd()*w,rnd()*h,1+rnd()*2,1)}for(let z=0;z<4;z++){c.fillStyle=['rgba(46,133,129,.10)','rgba(77,112,157,.10)','rgba(100,111,137,.10)','rgba(140,126,87,.09)'][z];c.fillRect(z%2*20*S,Math.floor(z/2)*15*S,20*S,15*S)}c.lineWidth=1;c.strokeStyle='rgba(14,26,35,.2)';for(let x=0;x<=40;x+=5){c.beginPath();c.moveTo(x*S,0);c.lineTo(x*S,h);c.stroke()}for(let y=0;y<=30;y+=5){c.beginPath();c.moveTo(0,y*S);c.lineTo(w,y*S);c.stroke()}
 const outline=(cell,color,label)=>{let [x,y]=cell;c.strokeStyle=color;c.lineWidth=2;c.strokeRect((x+.12)*S,(y+.12)*S,.76*S,.76*S);if(label){c.font='bold '+Math.round(S*.20)+'px sans-serif';c.fillStyle=color;c.textAlign='center';c.fillText(label,(x+.5)*S,(y+.78)*S)}};
 map.parking.forEach((p,i)=>outline(p,'#d1d8d9',String(i+1).padStart(2,'0')));map.pickups.forEach(p=>outline(p,'#8cc2ac','P'));map.dropoffs.forEach(p=>outline(p,'#9cbbd5','D'));Object.values(map.queue_cells).flat().forEach((p,i)=>outline(p,'#c8b57f','Q'+(i%4+1)));
 for(let z=0;z<4;z++){c.font='600 '+Math.round(S*.42)+'px sans-serif';c.fillStyle='#cad3d4';c.textAlign='center';c.fillText('ZONE '+z,(z%2*20+10)*S,(Math.floor(z/2)*28.3+.65)*S)}
 })}
function rackComponents(){const todo=new Set(map.walls.map(key)),out=[];while(todo.size){const k=todo.values().next().value;todo.delete(k);const cells=[k.split(',').map(Number)];for(let i=0;i<cells.length;i++){let [x,y]=cells[i];for(const c of [[x-1,y],[x+1,y],[x,y-1],[x,y+1]])if(todo.delete(key(c)))cells.push(c)}out.push(cells)}return out}
function addRack(cells,index){const g=new THREE.Group();world.add(g);const upright=[],beams=[],decks=[],cartons=[],safety=[],rnd=seeded(1701+index),walls=new Set(map.walls.map(key));for(const [x,z] of cells){for(const dx of [.1,.9])for(const dz of [.1,.9])upright.push({at:[x+dx,1.36,z+dz],scale:[.065,2.65,.065]});for(const y of [.23,1.06,1.89]){for(const dz of [.1,.9])beams.push({at:[x+.5,y,z+dz],scale:[.85,.12,.08]});for(let i=0;i<4;i++)decks.push({at:[x+.5,y+.075,z+.2+i*.2],scale:[.78,.035,.09]});if(rnd()>.21){const height=.32+rnd()*.28;cartons.push({at:[x+.32,y+.105+height/2,z+.49],scale:[.3+rnd()*.08,height,.55+rnd()*.12],color:new THREE.Color().setHSL(.09,.22,.53+rnd()*.16).getHex()});if(rnd()>.3)cartons.push({at:[x+.72,y+.33,z+.53],scale:[.27,.43,.48],color:0xc2a482})}}for(const [dx,dz] of [[-1,0],[1,0],[0,-1],[0,1]])if(!walls.has(key([x+dx,z+dz])))safety.push({at:[x+.5+dx*.472,.024,z+.5+dz*.472],scale:dx?[.024,.012,.94]:[.94,.012,.024]})}
 const ms=[new THREE.MeshStandardMaterial({color:palette.blue,roughness:.57,metalness:.25}),new THREE.MeshStandardMaterial({color:palette.orange,roughness:.65}),new THREE.MeshStandardMaterial({color:0x8a8d80,roughness:.8}),new THREE.MeshStandardMaterial({map:sharedTex.carton,roughness:.92})];ms.forEach(m=>ownedMaterial(g,m));instanced(g,upright,ms[0],boxGeo,true);instanced(g,beams,ms[1],boxGeo,true);instanced(g,decks,ms[2]);instanced(g,cartons,ms[3],boxGeo,true);instanced(world,safety,mat(palette.yellow));g.userData.rackCells=cells;g.userData.rackMaterials=ms;rackGroups.push(g);
 const p=cells.reduce((a,b)=>b[1]<a[1]?b:a,cells[0]);const sign=textSprite('A'+(index+1),p,'#e3edf2',.21);sign.position.set(p[0]+.5,2.7,p[1]+.2);g.add(sign);
}
function buildWorld(){if(!scene)return;visualAssets();if(world?.userData.selection)clean(world.userData.selection);for(const g of [world,dynamic,routeLayer,resLayer,heatLayer,taskLayer])clean(g);for(const g of robots.values()){g.userData.label.remove();clean(g)}robots.clear();portMeshes.clear();visualPort.clear();rackGroups=[];$('labels').replaceChildren();$('labelLeaders').replaceChildren();world=new THREE.Group();scene.add(world);world.userData.textures=[];
 const tex=stampFloor();world.userData.textures.push(tex);floorMaterial=ownedMaterial(world,new THREE.MeshStandardMaterial({map:tex,roughness:.6,metalness:.12}));const floor=new THREE.Mesh(sharedGeo.plane,floorMaterial);floor.rotation.x=-Math.PI/2;floor.scale.set(40,30,1);floor.position.set(20,0,15);floor.receiveShadow=true;world.add(floor);box(world,[19.5,14.5],40,.22,30,0x253442,-.235);
 grid=new THREE.Group();world.add(grid);const vertices=[];for(let x=0;x<=40;x++)vertices.push(x,.016,0,x,.016,30);for(let y=0;y<=30;y++)vertices.push(0,.016,y,40,.016,y);const gg=new THREE.BufferGeometry();gg.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));const gl=new THREE.LineSegments(gg,new THREE.LineBasicMaterial({color:0xc5d5dc,transparent:true,opacity:.12}));gl.userData.ownGeo=true;gl.userData.lineMat=true;grid.add(gl);grid.visible=flags.grid;
 // Kệ và hàng đều nằm trong [x+.05,x+.95] × [y+.05,y+.95] của từng wall.
 rackComponents().forEach(addRack);
 const contact=ownedMaterial(world,new THREE.MeshBasicMaterial({map:sharedTex.contact,transparent:true,depthWrite:false,color:0x000000}));instanced(world,map.walls.map(([x,z])=>({at:[x+.5,.007,z+.5],rot:[-Math.PI/2,0,0],scale:[.98,.98,1]})),contact,sharedGeo.plane);
 const structure=[],trim=[],lights=[];for(const z of [-.42,30.42]){structure.push({at:[20,.28,z],scale:[41,.56,.2]});for(let x=0;x<=40;x+=8){structure.push({at:[x,1.6,z],scale:[.18,3.2,.18]});lights.push({at:[x,3.05,z],scale:[2.2,.04,.1]})}}for(const x of [-.42,40.42]){structure.push({at:[x,.28,15],scale:[.2,.56,30.8]});for(let z=6;z<30;z+=8)structure.push({at:[x,1.6,z],scale:[.18,3.2,.18]})}instanced(world,structure,mat(0x344c60));instanced(world,lights,ownedMaterial(world,new THREE.MeshBasicMaterial({color:0xa4c7d2})));const board=textSprite('FULFILLMENT  /  FLEET OPERATIONS',[19.5,-.85],'#b5cbd5',.5);board.position.y=2.8;world.add(board);
 // Các cơ cấu giao nhận nằm ở dải mép ô; tâm ô chừa cho AMR (không thêm chướng ngại).
 for(const [cells,type,color] of [[map.pickups,'P',0x659f89],[map.dropoffs,'D',0x728fab]])for(const c of cells){const pole=box(world,[c[0]+.46,c[1]-.44],.035,1.1,.035,0x7f9198);trim.push({at:[c[0]+.5,.032,c[1]+.5],scale:[.88,.025,.88],color:type==='P'?0x536e67:0x536673});const s=textSprite(type,c,'#dce9e8',.3);s.position.set(c[0]+.93,1.33,c[1]+.12);world.add(s);for(let i=0;i<4;i++)trim.push({at:[c[0]+.2+i*.2,.1,c[1]+.045],scale:[.15,.06,.055],color:type==='P'?0xa18f72:0x9aaab4})}instanced(world,trim,mat(0xffffff));
 for(const p of map.ports){const c=p.cell;const pad=box(world,c,.88,.024,.88,0x3b5960,.025);portMeshes.set(p.id,pad);const cabinet=box(world,[c[0],c[1]-.490],.74,.55,.016,0x516675,.05);cabinet.castShadow=true;const stripe=new THREE.Mesh(boxGeo,ownedMaterial(world,new THREE.MeshStandardMaterial({map:sharedTex.hazard,roughness:.85})));stripe.scale.set(.87,.04,.05);stripe.position.set(c[0]+.5,.04,c[1]+.96);world.add(stripe);const ledMat=ownedMaterial(world,new THREE.MeshBasicMaterial({color:0x6e828c})),led=new THREE.Mesh(boxGeo,ledMat);led.scale.set(.48,.055,.014);led.position.set(c[0]+.5,.49,c[1]+.024);world.add(led);const ring=new THREE.Mesh(sharedGeo.energyRing,ownedMaterial(world,new THREE.MeshBasicMaterial({color:0x66e2b2,transparent:true,opacity:.7,depthWrite:false,side:THREE.DoubleSide})));ring.rotation.x=-Math.PI/2;ring.position.set(c[0]+.5,.057,c[1]+.5);world.add(ring);const sign=textSprite('C'+p.id+' · TRỐNG',[c[0],c[1]],'#cfdddf',.18);sign.position.set(c[0]+.5,.85,c[1]+.05);world.add(sign);visualPort.set(p.id,{led,ring,sign,last:''})}
 $('mapTitle').textContent='MAP '+map.name+' · 40 × 30 m';lastVisualT=null;fitCamera();setQuality();
}
function robotGeometry(kind){const cache='robot'+kind;if(sharedGeo[cache])return sharedGeo[cache];const length={L:.60,M:.75,H:.90}[kind],width={L:.42,M:.48,H:.54}[kind],height={L:.16,M:.21,H:.25}[kind],color={L:0x60b7bb,M:0x888cac,H:0xc69b66}[kind];const parts=[];const body=roundedShape(width,length,height,.075);parts.push({geo:body,at:[0,.12,0],color});const add=(at,scale,color,geo=boxGeo,rot=[0,0,0])=>parts.push({geo,at,scale,color,rot});add([0,.12,0],[width*.94,.13,length*.93],0x23313b);for(const x of [-width/2,width/2])for(const z of [-length*.28,length*.28])add([x,.105,z],[.082,.065,.082],0x111923,sharedGeo.cylinder,[0,0,Math.PI/2]);add([0,height+.16,0],[width*.87,.055,length*.8],0xc0c9c9);for(let i=0;i<(kind==='H'?6:4);i++)add([0,height+.2,-length*.30+i*(length*.6/(kind==='H'?5:3))],[width*.76,.025,.035],0x71818b);add([0,.20,length*.47],[width*.4,.055,.033],0x111d27);add([0,height+.19,length*.36],[.052,.045,.052],0x283b4a,sharedGeo.cylinder);add([.05,.21,length*.495],[.025,.018,.008],0x87e7e5);if(kind==='H')for(const x of [-width*.42,width*.42])add([x,height+.27,0],[.034,.10,length*.78],0x566774);if(kind==='M')add([0,.24,-length*.43],[width*.7,.10,.035],0x616b82);sharedGeo[cache]=mergeParts(parts);const a=sharedGeo[cache].attributes.position;for(let i=0;i<a.count;i++){const x=a.getX(i),z=a.getZ(i),radius=Math.hypot(x,z);if(radius>.472)a.setXYZ(i,x*.472/radius,a.getY(i),z*.472/radius)}a.needsUpdate=true;sharedGeo[cache].computeVertexNormals();body.dispose();return sharedGeo[cache]}
function robotModel(r){visualAssets();const g=new THREE.Group(),body=new THREE.Group();g.add(body);const mesh=new THREE.Mesh(robotGeometry(r.type),visualMaterials().robot);mesh.castShadow=true;body.add(mesh);const width={L:.42,M:.48,H:.54}[r.type],length={L:.60,M:.75,H:.90}[r.type],h={L:.16,M:.21,H:.25}[r.type];const ledGeoKey='led'+r.type;if(!sharedGeo[ledGeoKey])sharedGeo[ledGeoKey]=mergeParts([-.5,.5].flatMap(s=>[{geo:boxGeo,at:[s*width,.18,0],scale:[.013,.02,length*.75]},{geo:boxGeo,at:[0,.18,s*length*.96],scale:[width*.75,.02,.013]}]));const led=new THREE.Mesh(sharedGeo[ledGeoKey],ownedMaterial(g,new THREE.MeshBasicMaterial({color:0xa1cec9})));body.add(led);const cargo=new THREE.Mesh(boxGeo,visualMaterials().carton);cargo.position.y=h+.38;body.add(cargo);const contact=new THREE.Mesh(sharedGeo.plane,visualMaterials().contact);contact.rotation.x=-Math.PI/2;contact.scale.set(.85,.96,1);contact.position.y=.009;g.add(contact);const highlight=new THREE.Mesh(sharedGeo.ring,visualMaterials().highlight);highlight.rotation.x=-Math.PI/2;highlight.position.y=.04;g.add(highlight);const el=document.createElement('div');el.className='rlabel';el.innerHTML='<span></span><i></i>';$('labels').append(el);g.userData={...g.userData,cargo,body,led,highlight,id:r.id,kind:r.type,label:el,heading:0,oldHeading:0,changedAt:time,previousStatus:r.status,bodyHeight:h};scene.add(g);return g}
let visualMats;
function visualMaterials(){if(!visualMats)visualMats={robot:new THREE.MeshStandardMaterial({vertexColors:true,roughness:.5,metalness:.24}),carton:new THREE.MeshStandardMaterial({map:sharedTex.carton,roughness:.94}),contact:new THREE.MeshBasicMaterial({map:sharedTex.contact,transparent:true,depthWrite:false,color:0x000000}),highlight:new THREE.MeshBasicMaterial({color:0x75e9d3,transparent:true,opacity:.9,side:THREE.DoubleSide,depthWrite:false})};return visualMats}
function updateRobotAppearance(r,g){const d=g.userData;d.cargo.visible=r.load_kg>0;const a=Math.min(1,r.load_kg/(r.payload_capacity_kg??specs[r.type].payload_capacity_kg));const scale=.55+.4*Math.sqrt(a),width={L:.42,M:.48,H:.54}[r.type],length={L:.60,M:.75,H:.90}[r.type];d.cargo.scale.set(width*.8*scale,.15+.23*a,length*.58*scale);d.cargo.position.y=d.bodyHeight+.22+d.cargo.scale.y/2;const heading=r.move_to?Math.atan2(r.move_to[0]-r.cell[0],r.move_to[1]-r.cell[1]):d.heading;if(d.previousStatus!==r.status||heading!==d.heading){d.oldHeading=g.rotation.y;d.heading=heading;d.changedAt=frame.t;d.previousStatus=r.status}d.label.dataset.state=group(r.status);d.label.title='#'+r.id+' · '+r.type+' · '+group(r.status)+' · '+Math.round(r.soc*100)+'%';d.label.querySelector('i').style.width=(r.soc*100)+'%';d.led.material.color.setHex({IDLE:0xb5cfce,WORK:0x6edbac,CHARGE:0x6dbde5,HOLD:0xe1a25e}[group(r.status)])}
function roadArrow(parent,a,b,color=0xd2bf77){if(eq(a,b))return;const angle=Math.atan2(b[0]-a[0],b[1]-a[1]);const pts=[[-.18,-.12],[0,.12],[.18,-.12]].map(([x,z])=>[a[0]+x*Math.cos(angle)+z*Math.sin(angle),a[1]-x*Math.sin(angle)+z*Math.cos(angle)]);line(parent,pts,color,.075)}
function blockedMarker(c){const entries=[];for(let i=0;i<5;i++)entries.push({at:[c[0]+.2+i*.15,.06,c[1]+.5],scale:[.06,.025,.78],rot:[0,-.3,0],color:i%2?0xd2d4cf:0xb66c65});instanced(dynamic,entries,mat(0xffffff));const coneGeo=new THREE.ConeGeometry(.105,.3,8),cone=new THREE.Mesh(coneGeo,mat(0xc78258));cone.position.set(c[0]+.16,.21,c[1]+.15);cone.userData.ownGeo=true;dynamic.add(cone);const s=textSprite('! BLOCK',c,'#efc4b4',.2);s.position.y=.55;dynamic.add(s)}
function applyFrame(f){frame=f;for(const [id,g] of robots)if(!f.robots.some(r=>r.id===id)){g.userData.label.remove();clean(g);robots.delete(id)}for(const r of f.robots){let g=robots.get(r.id);if(!g){g=robotModel(r);robots.set(r.id,g)}updateRobotAppearance(r,g)}
 for(const g of [dynamic,routeLayer,resLayer,heatLayer,taskLayer])clean(g);dynamic=new THREE.Group();routeLayer=new THREE.Group();resLayer=new THREE.Group();heatLayer=new THREE.Group();taskLayer=new THREE.Group();scene.add(dynamic,routeLayer,resLayer,heatLayer,taskLayer);
 for(const c of f.blocked_cells??[])blockedMarker(c);for(const e of [...map.blocked_edges,...f.blocked_edges??[]]){line(dynamic,e,0xd17f74,.12);const a=e[0],b=e[1],p=[(a[0]+b[0])/2,(a[1]+b[1])/2];line(dynamic,[[p[0]-.2,p[1]-.2],[p[0]+.2,p[1]+.2]],0xebe1d6,.14)}
 // Route là kế hoạch đã biết; reservation vẫn dùng danh sách riêng của snapshot.
 const routeVertices=[],selectedVertices=[];for(const r of f.robots){if(r.route?.length){const verts=r.id===selected?selectedVertices:routeVertices;for(let i=0;i<r.route.length-1;i++){const a=r.route[i],b=r.route[i+1];verts.push(a[0]+.5,.065,a[1]+.5,b[0]+.5,.065,b[1]+.5);if(i%3===0){const angle=Math.atan2(b[0]-a[0],b[1]-a[1]),pts=[[-.13,-.12],[0,.09],[.13,-.12]].map(([x,z])=>[a[0]+.5+x*Math.cos(angle)+z*Math.sin(angle),.075,a[1]+.5-x*Math.sin(angle)+z*Math.cos(angle)]);verts.push(...pts[0],...pts[1],...pts[1],...pts[2])}}}if((r.paused_until_s??0)>f.t||r.status==='hold')line(dynamic,[[r.cell[0]-.4,r.cell[1]-.4],[r.cell[0]+.4,r.cell[1]-.4],[r.cell[0]+.4,r.cell[1]+.4],[r.cell[0]-.4,r.cell[1]+.4],[r.cell[0]-.4,r.cell[1]-.4]],0xd4aa75,.04)}for(const [vertices,opacity] of [[routeVertices,.28],[selectedVertices,.75]])if(vertices.length){const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));const l=new THREE.LineSegments(geo,new THREE.LineBasicMaterial({color:0x78c0b5,transparent:true,opacity}));l.userData.ownGeo=true;l.userData.lineMat=true;routeLayer.add(l)}
 instanced(resLayer,(f.reservations??[]).map(v=>({at:[v.cell[0]+.5,.031,v.cell[1]+.5],scale:[.83,.006,.83]})),mat(0x637688));instanced(heatLayer,(f.heatmap??[]).map(h=>({at:[h.cell[0]+.5,.039,h.cell[1]+.5],scale:[.92,.006,.92],color:new THREE.Color().setHSL(.12*(1-Math.min(1,h.value)),.5,.4).getHex()})),mat(0xffffff));
 for(const c of f.corridors??[]){line(dynamic,c.cells,0xcdb779,.044);for(const p of c.passing_cells??[]){line(dynamic,[[p[0]-.3,p[1]-.3],[p[0]+.3,p[1]+.3]],0xcdb779,.047);line(dynamic,[[p[0]-.3,p[1]+.3],[p[0]+.3,p[1]-.3]],0xcdb779,.047)}if(c.direction&&c.cells.length>1)roadArrow(dynamic,...c.direction)}
 const cartons=[];for(const t of f.tasks)if(['waiting','assigned','pending'].includes(t.state)){// Bàn nhỏ sát mép cell, không chiếm thể tích đường chạy AMR.
 cartons.push({at:[t.pickup[0]+.5,.23,t.pickup[1]+.045],scale:[.34,.28,.065],color:t.priority===3?0xe0c192:0xb99b73});const s=textSprite('T'+t.id+' · P'+t.priority+' · '+(f.t-t.created).toFixed(0)+'s',t.pickup,t.priority===3?'#f0cd8f':'#c5d5df',.18);s.position.y=1.65;taskLayer.add(s)}instanced(taskLayer,cartons,visualMaterials().carton);
 UI(f);drawSelection();updatePortAppearance();scene.traverse(o=>{if(o.isSprite)o.visible=flags.labels});}
function updatePortAppearance(){for(const p of map.ports){const v=frame.ports.find(x=>x.id===p.id),a=visualPort.get(p.id),charging=v?.charging_robot!=null,occupied=v?.occupied_by!=null,label='C'+p.id+' · '+(charging?'NẠP':occupied?'CHIẾM':'TRỐNG');a.led.material.color.setHex(charging?0x70dfae:occupied?0xe8b66d:0x617680);a.ring.visible=charging;if(a.last!==label){const old=a.sign,sign=textSprite(label,p.cell,charging?'#abebcc':occupied?'#ebc48d':'#b2c2c6',.18);sign.position.copy(old.position);world.add(sign);clean(old);a.sign=sign;a.last=label}}}
function layoutLabels(){const leaders=[],w=$('view').clientWidth,h=$('view').clientHeight-56,occupied=[],ordered=[...frame.robots].sort((a,b)=>(b.id===selected)-(a.id===selected)||robots.get(a.id).position.distanceToSquared(camera.position)-robots.get(b.id).position.distanceToSquared(camera.position));for(const r of ordered){const g=robots.get(r.id),el=g.userData.label,distance=g.position.distanceTo(camera.position),full=flags.fullLabels||r.id===selected||r.id===hovered||distance<15;const text=full?'#'+r.id+' '+r.type+' · '+group(r.status)+' · '+Math.round(r.soc*100)+'%'+(r.load_kg?' · '+r.load_kg+'kg':''):'#'+r.id;el.querySelector('span').textContent=text;el.classList.toggle('selected',r.id===selected);el.setAttribute('aria-label',el.title);const pos=g.position.clone().add(new THREE.Vector3(0,.85,0)).project(camera);let x=(pos.x*.5+.5)*w,y=(-pos.y*.5+.5)*h,bw=full?Math.max(140,text.length*5.8+12):34,bh=full?29:24;if(!flags.labels||pos.z>1||pos.z< -1||x<0||x>w||y<18||y>h-20){el.style.display='none';continue}const anchorX=x,anchorY=y;x=Math.max(bw/2+6,Math.min(w-bw/2-6,x));let found=false;for(let j=0;j<16;j++){const yy=y-j*26,rect={x:x-bw/2,y:yy-bh,w:bw,h:bh};if(yy<35)break;if(!occupied.some(o=>rect.x<o.x+o.w+3&&rect.x+rect.w+3>o.x&&rect.y<o.y+o.h+3&&rect.y+rect.h+3>o.y)){y=yy;occupied.push(rect);found=true;break}}if(!found){el.style.display='none';continue}el.style.display='block';el.style.left=x+'px';el.style.top=y+'px';el.style.width=bw+'px';el.style.opacity=full?'1':String(Math.max(.62,1-distance/180));el.style.zIndex=r.id===selected?4:2;if(Math.abs(y-anchorY)>12)leaders.push('<line x1="'+anchorX.toFixed(1)+'" y1="'+anchorY.toFixed(1)+'" x2="'+x.toFixed(1)+'" y2="'+y.toFixed(1)+'" stroke="#87b8c1" stroke-opacity=".32" stroke-width=".7"/>')}$('labelLeaders').innerHTML=leaders.join('')}
function updateVisuals(t){if(!frame)return;const dt=lastVisualT==null?0:t-lastVisualT;lastVisualT=t;for(const r of frame.robots){const g=robots.get(r.id),d=g.userData;let progress=Math.min(1,Math.max(0,(t-d.changedAt)/.22));let delta=Math.atan2(Math.sin(d.heading-d.oldHeading),Math.cos(d.heading-d.oldHeading));g.rotation.y=d.oldHeading+delta*progress;if(dt<0||dt>1)g.rotation.y=d.heading;const phase=r.edge_duration_s?Math.min(1,Math.max(0,1-(r.move_remaining_s-Math.max(0,t-frame.t))/r.edge_duration_s)):0;d.body.rotation.x=r.move_to&&r.status!=='hold'?.014*Math.sin(phase*Math.PI*2):0;d.highlight.visible=r.id===selected;d.led.material.color.setHex({IDLE:0xb5cfce,WORK:0x6edbac,CHARGE:0x6dbde5,HOLD:0xe1a25e}[group(r.status)]);d.led.material.color.multiplyScalar(group(r.status)==='CHARGE'?.72+.28*Math.sin(t*5)**2:1);if(r.status==='pickup'||r.status==='dropoff')d.cargo.position.y=d.bodyHeight+.22+d.cargo.scale.y/2+.025*Math.sin(Math.min(1,(t-frame.t)/.5)*Math.PI)}for(const a of visualPort.values())if(a.ring.visible){a.ring.material.opacity=.35+.4*Math.sin(t*4)**2;a.led.material.color.setRGB(.3,.65+.25*Math.sin(t*4)**2,.48)}
 // Xuyên kệ chỉ tác động material, không thay occupancy hay mô hình dữ liệu.
 for(const g of rackGroups){const selectedRobot=robots.get(selected);let fade=false;if(flags.xray&&selectedRobot){const ray=new THREE.Ray(camera.position,selectedRobot.position.clone().sub(camera.position).normalize()),box=new THREE.Box3().setFromObject(g),hit=ray.intersectBox(box,new THREE.Vector3());fade=!!hit&&hit.distanceTo(camera.position)<selectedRobot.position.distanceTo(camera.position)}for(const m of g.userData.rackMaterials){m.transparent=fade;m.opacity=fade?.055:1;m.depthWrite=!fade}g.castShadow=!fade}
 layoutLabels();}
function setQuality(){if(!renderer||!sun)return;const q=QUALITY[$('quality')?.value??'medium'];renderer.setPixelRatio(Math.min(devicePixelRatio,q.dpr));const enabled=q.shadow>0;renderer.shadowMap.enabled=enabled;sun.castShadow=enabled;if(enabled&&sun.shadow.mapSize.x!==q.shadow){sun.shadow.mapSize.set(q.shadow,q.shadow);sun.shadow.map?.dispose();sun.shadow.map=null}renderer.shadowMap.needsUpdate=true;}
function fitCamera(){if(!camera||!target)return;theta=.72;phi=.64;target.set(20,0,15);const vf=THREE.MathUtils.degToRad(camera.fov),hf=2*Math.atan(Math.tan(vf/2)*camera.aspect);radius=Math.max(51,24/Math.sin(Math.min(vf,hf)/2));}

function drawSelection(){if(!frame)return;const r=frame.robots.find(r=>r.id===selected);$('detail').textContent=r?JSON.stringify({id:r.id,type:r.type,status:r.status,load_kg:r.load_kg,soc:r.soc,capacity_wh:r.capacity_wh??null,battery_wh:r.battery_wh??null,task_id:r.task_id,target_soc:r.target_soc,move_to:r.move_to??null,move_remaining_s:r.move_remaining_s??null,bookings:frame.ports.flatMap(p=>(p.bookings??[]).filter(b=>b.robot_id===r.id).map(b=>({port:p.id,...b}))).slice(-4)},null,2):'Chọn robot';if(world.userData.selection)clean(world.userData.selection);}
function UI(f){$('mode').textContent=live?'LIVE':'REPLAY';$('metrics').replaceChildren();for(const [k,label] of [['throughput_per_hour','Throughput / h'],['pending','Pending'],['total_lateness_s','Tổng trễ · s'],['mean_charge_wait_s','Chờ sạc TB · s'],['fallback_count','Số fallback']]){let d=document.createElement('div');d.className='metric';let b=document.createElement('b');b.textContent=Number.isFinite(f.kpi?.[k])?Number(f.kpi[k].toFixed(2)):'—';let s=document.createElement('span');s.textContent=label;d.append(b,s);$('metrics').append(d)}$('robotList').replaceChildren();for(const r of f.robots){const o=new Option('#'+r.id+' · '+r.type+' · '+group(r.status),r.id);o.selected=r.id===selected;$('robotList').add(o)}$('ports').replaceChildren();for(const p of map.ports){let v=f.ports.find(v=>v.id===p.id),charging=v?.charging_robot!=null,occupied=v?.occupied_by!=null;portMeshes.get(p.id).material=mat(charging?0x36d2a6:occupied?0xeeb761:0x466070);let d=document.createElement('div');d.className='port '+(charging?'charge':occupied?'occupied':'');let title=document.createElement('b');title.textContent='C'+p.id+' · '+(charging?'NẠP #'+v.charging_robot:occupied?'BỊ CHIẾM #'+v.occupied_by:'TRỐNG');let info=document.createElement('pre');info.textContent=p.power_w+' W · '+p.compatible.join('/')+'\nQueue: '+(v?.queue_robot_ids?JSON.stringify(v.queue_robot_ids):'—')+'\n'+(v?.bookings??[]).map(b=>'#'+b.robot_id+' ['+b.start+' → '+b.end+'] kế hoạch').join('\n');d.append(title,info);$('ports').append(d)}const logs=frames.slice(0,idx+1).filter(x=>x.decision).slice(-8);$('log').textContent=logs.map(x=>x.t+'s · P'+(x.decision.profile??'—')+' · '+x.decision.solver_status+'\n'+(x.decision.fallback_reason??'')).join('\n');$('notice').textContent=''}
// Chỉ dùng chuyển động đã bắt đầu trong frame hiện tại; tuyệt đối không đọc frame tương lai để suy vị trí.
function interpolate(t){if(!frame)return;for(const r of frame.robots){let x=r.cell[0],z=r.cell[1];if(r.move_to&&r.edge_duration_s>0){const elapsed=Math.max(0,t-frame.t);let a=Math.min(1,Math.max(0,1-(r.move_remaining_s-elapsed)/r.edge_duration_s));if((r.paused_until_s??0)>frame.t||r.status==='hold')a=Math.max(0,1-r.move_remaining_s/r.edge_duration_s);x+=(r.move_to[0]-x)*a;z+=(r.move_to[1]-z)*a}const g=robots.get(r.id);g.position.set(x+.5,0,z+.5);}grid.visible=flags.grid;routeLayer.visible=flags.routes;resLayer.visible=flags.reservations;heatLayer.visible=flags.heatmap;updateVisuals(t);}

function update(){if(!frames.length)return;let lo=0,hi=frames.length-1;while(lo<hi){let mid=Math.ceil((lo+hi)/2);if(frames[mid].t<=time)lo=mid;else hi=mid-1}if(idx!==lo){idx=lo;applyFrame(frames[idx])}$('clock').textContent=time.toFixed(1)+' s';$('seek').value=time}
let theta=.73,phi=.72,radius=49,target;
function cameraUpdate(){const mode=$('cameraMode').value;if(mode==='follow'&&robots.has(selected)){const p=robots.get(selected).position;camera.position.copy(p).add(new THREE.Vector3(-3.4,4.3,4.2));camera.lookAt(p)}else if(mode==='top'){camera.position.set(target.x,Math.max(22,radius*.68),target.z+.01);camera.lookAt(target)}else{camera.position.set(target.x+radius*Math.sin(phi)*Math.sin(theta),radius*Math.cos(phi),target.z+radius*Math.sin(phi)*Math.cos(theta));camera.lookAt(target)}camera.updateMatrixWorld();}
function init(){boxGeo=new THREE.BoxGeometry(1,1,1);scene=new THREE.Scene();scene.background=new THREE.Color(0x101c29);scene.fog=new THREE.FogExp2(0x101c29,.003);camera=new THREE.PerspectiveCamera(42,1,.1,200);target=new THREE.Vector3(20,0,15);renderer=new THREE.WebGLRenderer({antialias:true});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('view').prepend(renderer.domElement);scene.add(new THREE.HemisphereLight(0xc4dae7,0x425060,2.3));sun=new THREE.DirectionalLight(0xffeddb,2.7);sun.position.set(4,30,9);sun.target.position.set(20,0,15);sun.shadow.camera.left=-28;sun.shadow.camera.right=28;sun.shadow.camera.top=25;sun.shadow.camera.bottom=-25;sun.shadow.camera.near=1;sun.shadow.camera.far=70;sun.shadow.bias=-.00025;sun.shadow.normalBias=.02;sun.shadow.radius=2;scene.add(sun,sun.target);setQuality();
 const resize=()=>{const w=$('view').clientWidth,h=$('view').clientHeight-56;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);fitCamera()};new ResizeObserver(resize).observe($('view'));resize();for(const [k,v] of Object.entries(flags)){const l=document.createElement('label');l.className='toggle';const i=document.createElement('input');i.type='checkbox';i.checked=v;i.onchange=()=>{flags[k]=i.checked;if(k==='labels')scene.traverse(o=>{if(o.isSprite)o.visible=i.checked})};l.append(i,document.createTextNode(({grid:'Lưới',labels:'Nhãn',routes:'Route',reservations:'Đặt chỗ',heatmap:'Tắc nghẽn',fullLabels:'Nhãn đầy đủ',xray:'Xuyên kệ'})[k]??k));$('toggles').append(l)}let drag=null,moved=0;renderer.domElement.onpointerdown=e=>{drag=[e.clientX,e.clientY];moved=0;renderer.domElement.setPointerCapture(e.pointerId)};renderer.domElement.onpointermove=e=>{if(!drag){hoverRobot(e);return}const dx=e.clientX-drag[0],dy=e.clientY-drag[1];moved+=Math.abs(dx)+Math.abs(dy);if(e.shiftKey){target.x-=dx*.04;target.z-=dy*.04}else{theta-=dx*.006;phi=Math.max(.08,Math.min(1.4,phi+dy*.006))}drag=[e.clientX,e.clientY]};renderer.domElement.onpointerup=e=>{drag=null;if(moved>4)return;const b=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),camera);const hit=ray.intersectObjects([...robots.values()],true)[0];if(hit){let o=hit.object;while(o.parent&&o.userData.id===undefined)o=o.parent;selected=o.userData.id;$('robotList').value=selected;drawSelection()}};renderer.domElement.onwheel=e=>{e.preventDefault();radius=Math.max(10,Math.min(140,radius+e.deltaY*.035))};
 $('play').onclick=()=>{if(live)return;playing=!playing;$('play').textContent=playing?'Ⅱ Pause':'▶ Phát'};$('seek').oninput=()=>{if(!live){time=+$('seek').value;update()}};$('robotList').onchange=()=>{selected=+$('robotList').value;drawSelection()};
 $('quality').onchange=setQuality;$('resetCamera').onclick=()=>{$('cameraMode').value='orbit';fitCamera()};window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r'&&!/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)){$('cameraMode').value='orbit';fitCamera()}});loadMap(presetMap('A'));$('mode').textContent='CHỜ BẮT ĐẦU';let last=performance.now(),count=0,stamp=last;function animate(now){requestAnimationFrame(animate);const dt=(now-last)/1000;last=now;if(live&&frames.length&&!livePaused){const newest=frames.at(-1).t;if(!liveBuffered&&(newest-time>=1||liveFinished))liveBuffered=true;if(liveBuffered){time=Math.min(newest,time+Math.min(dt,.1)*liveSpeed);update();if(time>=newest&&!liveFinished)liveBuffered=false}}if(playing&&!live){time=Math.min(frames.at(-1).t,time+dt*+$('speed').value);if(time===frames.at(-1).t){playing=false;$('play').textContent='▶ Phát'}update()}interpolate(time);cameraUpdate();if(frame)layoutLabels();renderer.render(scene,camera);if(now-stamp>1000){$('fps').textContent=Math.round(count*1000/(now-stamp))+' FPS · '+renderer.info.render.calls+' draw calls';count=0;stamp=now}count++}requestAnimationFrame(animate);
}
// LIVE nhận frame từ host tin cậy qua API trực tiếp, không tự mở kết nối mạng.
export const viewer={loadMap,applyFrame,interpolate,install,validateFrame,presetMap,getState:()=>({time,idx,playing,isMock,live}),visualAudit:()=>({drawCalls:renderer?.info.render.calls,triangles:renderer?.info.render.triangles,quality:$('quality').value,robots:robots.size,positions:[...robots].map(([id,g])=>({id,x:g.position.x,z:g.position.z})),kpi:frame?.kpi}),pushLive(f,m){try{if(live&&frames.length&&f.t<=frames.at(-1).t)return;if(!live){assert(m,'Frame LIVE đầu cần map');install({map:m,frames:[f],mock:false});live=true}else{validateFrame(f,map,frames.at(-1));frames.push(f);if(frames.length>64){frames.shift();idx=Math.max(-1,idx-1)}}playing=false;$('mode').textContent='LIVE';$('seek').disabled=true;$('play').disabled=true}catch(e){error(e)}}};
function hoverRobot(e){const b=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),camera);const hit=ray.intersectObjects([...robots.values()],true)[0];hovered=null;if(hit){let o=hit.object;while(o.parent&&o.userData.id===undefined)o=o.parent;hovered=o.userData.id}renderer.domElement.style.cursor=hovered==null?'grab':'pointer'}
try{init()}catch(e){error(e)}

export function resetLive(){live=false;playing=false;frames=[];idx=-1;liveBuffered=false;livePaused=false;liveFinished=false;}
export function setLivePlayback(speed,paused,finished){liveSpeed=speed;livePaused=paused;liveFinished=finished;}
export function pickCell(event){const b=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((event.clientX-b.left)/b.width*2-1,-(event.clientY-b.top)/b.height*2+1),camera);const p=new THREE.Vector3();if(!ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),p))return null;return [Math.floor(p.x),Math.floor(p.z)];}
